[2024-04-22T09:21:19.003+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-22T09:20:27.729791+00:00 [queued]>
[2024-04-22T09:21:19.011+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-22T09:20:27.729791+00:00 [queued]>
[2024-04-22T09:21:19.012+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-04-22T09:21:19.026+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_Data_Submission_Reddit> on 2024-04-22 09:20:27.729791+00:00
[2024-04-22T09:21:19.031+0000] {standard_task_runner.py:60} INFO - Started process 19068 to run task
[2024-04-22T09:21:19.034+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'get_Data_Submission_Reddit', 'manual__2024-04-22T09:20:27.729791+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmpw0t870qd']
[2024-04-22T09:21:19.036+0000] {standard_task_runner.py:88} INFO - Job 120: Subtask get_Data_Submission_Reddit
[2024-04-22T09:21:19.075+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.get_Data_Submission_Reddit manual__2024-04-22T09:20:27.729791+00:00 [running]> on host d4c97f52cb78
[2024-04-22T09:21:19.163+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='get_Data_Submission_Reddit' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T09:20:27.729791+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-22T09:20:27.729791+00:00'
[2024-04-22T09:21:19.206+0000] {logging_mixin.py:188} INFO - True
[2024-04-22T09:21:22.913+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 40, in _get_Data_Submission_Reddit
    "submission_Author":submission.author.name,
AttributeError: 'NoneType' object has no attribute 'name'
[2024-04-22T09:21:22.920+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=get_Data_Submission_Reddit, execution_date=20240422T092027, start_date=20240422T092119, end_date=20240422T092122
[2024-04-22T09:21:22.934+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 120 for task get_Data_Submission_Reddit ('NoneType' object has no attribute 'name'; 19068)
[2024-04-22T09:21:22.978+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-22T09:21:23.005+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
