[2024-04-23T09:47:07.527+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres scheduled__2024-04-21T17:00:00+00:00 [queued]>
[2024-04-23T09:47:07.612+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres scheduled__2024-04-21T17:00:00+00:00 [queued]>
[2024-04-23T09:47:07.613+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-04-23T09:47:07.808+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2024-04-21 17:00:00+00:00
[2024-04-23T09:47:07.837+0000] {standard_task_runner.py:60} INFO - Started process 374 to run task
[2024-04-23T09:47:07.911+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'get_Data_Submission_Reddit_pipeline', 'load_data_to_postgres', 'scheduled__2024-04-21T17:00:00+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/GetPost.py', '--cfg-path', '/tmp/tmprcmrz34r']
[2024-04-23T09:47:07.937+0000] {standard_task_runner.py:88} INFO - Job 269: Subtask load_data_to_postgres
[2024-04-23T09:47:08.375+0000] {task_command.py:423} INFO - Running <TaskInstance: get_Data_Submission_Reddit_pipeline.load_data_to_postgres scheduled__2024-04-21T17:00:00+00:00 [running]> on host 694ea5737885
[2024-04-23T09:47:09.006+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_Data_Submission_Reddit_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-04-21T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-21T17:00:00+00:00'
[2024-04-23T09:47:09.049+0000] {logging_mixin.py:188} INFO - /opt/***/dags/staging/Submission_Reddit_Data_2024-04-21T17:00:00+00:00.json
[2024-04-23T09:47:09.089+0000] {base.py:83} INFO - Using connection ID 'my_***_conn' for task execution.
[2024-04-23T09:47:09.168+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/GetPost.py", line 110, in _load_data_to_postgres
    cursor.execute(sql, (ID, Title, Score, Author, selftext, Create_Date))
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(1000)

[2024-04-23T09:47:09.262+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=get_Data_Submission_Reddit_pipeline, task_id=load_data_to_***, execution_date=20240421T170000, start_date=20240423T094707, end_date=20240423T094709
[2024-04-23T09:47:09.354+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 269 for task load_data_to_*** (value too long for type character varying(1000)
; 374)
[2024-04-23T09:47:09.524+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-23T09:47:10.149+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
